### ISSUE TITLE
Adding a header seems to remove all other headers

### ISSUE THREAD

**Issue by kadriaen** [scalapb/scalapb-grpcweb#45]
using version 0.4.1

I'm would like to pass a custom header to my webgrpc service, but when I do so following the example code, the call fails.
When executing the same call without the additional header param the call works just fine, looks like the simple act of adding a header breaks the request?

`
  val headers: Metadata = Metadata(
    "token" -> "MyToken"
  )

  val myStub = MyApiGrpcWeb.stub(
    Channels.grpcwebChannel(url)
  )

  myStub.myStream(
      Empty(),
      headers,  // adding this param breaks the request 
      so.streamObserver
    )
`

The headers on the request do seem to include my custom header (but the call fails on envoy), but it seems to be missing a number of other header parameters when compared to the same call without my custom header parameter (which works fine).

Am I using this feature correctly?

**Comment by thesamet** [comment]
It looks like your usage is correct. Try to further debug this: for example, try to use grpcweb direct (using Javascript) to isolate if the problem is with this library or with grpcweb itself, or envoy configuration.

**Comment by AlexITC** [comment]
We do use this way, which works fine, I haven't tried streams but I remember the code handling it it's the same.

```scala
    val metadata: Map[String, String] = metadataForRequest(request)
    api.getX(request, metadata.toJSDictionary)
```

**Comment by thesamet** [comment]
@kadriaen @AlexITC - is this issue still relevant?

**Comment by AlexITC** [comment]
Well, as I said, with unary requests I have no issues, and I haven't tried streams with metadata yet, but I'll test those today/tomorrow and get back to you.

**Comment by AlexITC** [comment]
We have confirmed that streaming works properly for us, we send many metadata headers similar to how we send those in unary calls.

**Comment by thesamet** [comment]
Great, thanks for confirming!
